# Generated by Django 3.1.7 on 2021-03-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210327_0257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
